### ISSUE TITLE
Feature Request: color indicator even if the tab is not selected

### ISSUE THREAD

**Issue by vdurante** [ocean-mars/things#2]
Without your addon:

![Image](https://github.com/user-attachments/assets/a96bb101-2c1f-4701-ad0d-c08e6cdcfa6a)

With your addon, it disappears. Would be cool to have some indication of the container even if the tab is not selected.

Thanks for the incredible mod.

**Comment by ocean-mars** [comment]
Are you using userChrome.css? If you do, remove mod & paste this code,

/* Selected-Tabs Theme */
.tab-background {
background-color: color-mix(
in srgb,
var(--identity-tab-color, var(--tab-group-color-gray-invert)) 15%,
transparent
) !important;
border: 2.5px solid
color-mix(
in srgb,
var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
transparent
) !important;
opacity: 0.8 !important;
border-left: 32px solid
color-mix(
in srgb,
var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
transparent
) !important;
}

**Comment by ocean-mars** [comment]
I'm using this userChrome

https://github.com/ocean-mars/things/blob/main/Zen%20Browser%20Tweaks/userChrome.css

**Comment by Neznak** [comment]
That code made all of my non-containered tabs to have a white border.
If you don't want your normal tabs to have borders, you can use this:

```css
@-moz-document url-prefix("chrome:") {
  .tab-context-line {
      display: none !important;
  }

  .tabbrowser-tab[usercontextid] .tab-background {
      background-color: color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 15%,
      transparent
      ) !important;

      border: 2.5px solid
      color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
      transparent
      ) !important;
  }
}
```
